export { API_PATH_PREFIX, buildApiUrl } from "./client";
export { fetchHealth } from "./health";
export type { HealthResponse } from "./health";
export {
  ApiError,
  changeAccountPassword,
  confirmPasswordReset,
  fetchCurrentUser,
  loginAccount,
  logoutAccount,
  registerAccount,
  requestPasswordReset,
} from "./auth";
export type {
  AuthSession,
  PasswordResetRequestResult,
  UserProfile,
} from "./auth";
export {
  archiveDocument,
  createBatchImport,
  createDocumentRelation,
  createTag,
  createTopic,
  deleteDocument,
  deleteDocumentRelation,
  deleteTag,
  deleteTopic,
  downloadDocuments,
  getDocument,
  getDocumentKnowledge,
  getDocumentVersion,
  importDocument,
  importDocumentFile,
  listDocumentRelations,
  listDocuments,
  listDocumentVersions,
  listTags,
  listTopics,
  restoreDocument,
  retryDocumentIndex,
  retryBatchImport,
  renameTag,
  searchDocuments,
  setDocumentFavorite,
  updateDocument,
  updateTopic,
} from "./documents";
export type {
  BatchJobResult,
  DocumentDetail,
  DocumentInput,
  DocumentKnowledge,
  DocumentListFilters,
  DocumentRelation,
  DocumentSummary,
  DocumentUpdateInput,
  DocumentVersion,
  ImportResult,
  ExportDownload,
  KnowledgeEntity,
  KnowledgePoint,
  KnowledgeRelation,
  SearchHit,
  SearchMode,
  SourceSnapshot,
  SourceType,
  StoredFilePayload,
  Tag,
  Topic,
} from "./documents";
