export { API_PATH_PREFIX, buildApiUrl } from "./client";
export { fetchHealth } from "./health";
export type { HealthResponse } from "./health";
export { subscribeUnauthorized } from "./auth-events";
export {
  ApiError,
  changeAccountPassword,
  confirmPasswordReset,
  fetchCurrentUser,
  loginAccount,
  logoutAccount,
  registerAccount,
  requestPasswordReset,
} from "./auth";
export type {
  AuthSession,
  PasswordResetRequestResult,
  UserProfile,
} from "./auth";
export {
  archiveDocument,
  createBatchImport,
  createDocumentRelation,
  createTag,
  createTopic,
  deleteDocument,
  deleteDocumentRelation,
  deleteTag,
  deleteTopic,
  downloadDocuments,
  getDocument,
  getDocumentKnowledge,
  getDocumentVersion,
  importDocument,
  importDocumentFile,
  listDocumentRelations,
  listDocuments,
  listDocumentVersions,
  listTags,
  listTopics,
  restoreDocument,
  retryDocumentIndex,
  retryBatchImport,
  renameTag,
  searchDocuments,
  setDocumentFavorite,
  updateDocument,
  updateTopic,
} from "./documents";
export type {
  BatchJobResult,
  DocumentDetail,
  DocumentInput,
  DocumentKnowledge,
  DocumentListFilters,
  DocumentRelation,
  DocumentSummary,
  DocumentUpdateInput,
  DocumentVersion,
  ImportResult,
  ExportDownload,
  KnowledgeEntity,
  KnowledgePoint,
  KnowledgeRelation,
  SearchHit,
  SearchMode,
  SourceSnapshot,
  SourceType,
  StoredFilePayload,
  Tag,
  Topic,
} from "./documents";
export {
  createSession,
  deleteSession,
  getSession,
  listMessageCitations,
  listPracticeRecords,
  listSessionFeedback,
  listSessionMessages,
  listSessions,
  listTaskResults,
  renameSession,
  saveSessionFeedback,
} from "./sessions";
export type {
  Citation,
  ConversationMessage,
  ConversationSession,
  FeedbackRating,
  FeedbackTarget,
  MessageRole,
  PracticeRecord,
  SessionFeedback,
  SessionStatus,
  TaskResult,
  TaskResultKind,
  TaskStatus,
} from "./sessions";
export {
  askAgentQuestion,
  cancelAgentRun,
  continueAgentRun,
  getAgentRun,
  listAgentRunEvents,
} from "./agent";
export type {
  AgentAnswer,
  AgentMode,
  AgentRun,
  AgentRunEvent,
  AnswerCitation,
  EvidenceStatus,
  QuestionInput,
  QuestionResult,
  RunEvaluation,
  RunEventQuery,
  RunStatus,
  RunStep,
} from "./agent";
